### ISSUE TITLE
Activation problem on linux

### ISSUE THREAD

**Issue by mthnglac** [dysquard/pgpa#6]
I can't activate it on linux. Wine is a problem as usual.

**Comment by mthnglac** [comment]
> Don't use wine, do it like this:
> 
>     * Download the MacOS activator
> 
>     * Open a terminal
> 
>     * Unzip it: `unzip ActivatorMac.zip`
> 
>     * Install `adb`: `sudo apt install adb`
> 
>     * Enable USB debugging on your phone
> 
>     * Plug it in
> 
>     * Run this, it should return `1` if `adb` can find the device: `adb devices|grep "unauthorized"|wc -l`
> 
>     * Now run this: `adb root`
>       _it will return `adbd cannot run as root in production builds` though exit status should be 0 (echo $?)_
> 
>     * Now find the inject.sh file on your phone: `adb shell find /sdcard/.chaozhuo.gameassistant2/inject.sh`
> 
>     * Then run it: `adb shell sh /sdcard/.chaozhuo.gameassistant2/inject.sh`
> 
> 
> The output looked like this:
> 
> > 28
> > com.panda.gamepad,com.panda.mouse,com.chaozhuo.gameassistant
> > cp: bad '/sdcard/.chaozhuo.gameassistant2/com.panda.mouseinject.dex': No such file or directory
> > cp: bad '/sdcard/.chaozhuo.gameassistant2/com.panda.mouselibinject.so': No such file or directory
> 
> Despite the errors, opening the Panda app it now shows as activated.

It worked, thanks.

**Comment by dysquard** [comment]
> Don't use wine, do it like this:
> 
> * Download the MacOS activator
> * Open a terminal
> * Unzip it: `unzip ActivatorMac.zip`
> * Install `adb`: `sudo apt install adb`
> * Enable USB debugging on your phone
> * Plug it in
> * Run this, it should return `1` if `adb` can find the device: `adb devices|grep "unauthorized"|wc -l`
> * Now run this: `adb root`
>   _it will return `adbd cannot run as root in production builds` though exit status should be 0 (echo $?)_
> * Now find the inject.sh file on your phone: `adb shell find /sdcard/.chaozhuo.gameassistant2/inject.sh`
> * Then run it: `adb shell sh /sdcard/.chaozhuo.gameassistant2/inject.sh`
> 
> The output looked like this:
> 
> > 28
> > com.panda.gamepad,com.panda.mouse,com.chaozhuo.gameassistant
> > cp: bad '/sdcard/.chaozhuo.gameassistant2/com.panda.mouseinject.dex': No such file or directory
> > cp: bad '/sdcard/.chaozhuo.gameassistant2/com.panda.mouselibinject.so': No such file or directory
> 
> Despite the errors, opening the Panda app it now shows as activated.

Little mistake about `adb devices|grep "unauthorized"|wc -l`. If it's >= 1 then there's device unauthorized, should authorize on phone.
Just use `adb devices` to check device status, if it's OK its status will be `device`.
Then just go on `adb shell sh /sdcard/.chaozhuo.gameassistant2/inject.sh`.

**Comment by marcussacana** [comment]
What the point of this activation?

**Comment by hoshi411** [comment]
thank you so much for making this so easy for Linux users.
I was even able to use adb connect over WiFi to activate Panda.  That is awesome.

**Comment by thefirefox12537** [comment]
I already made this auto script for Linux

**Comment by marcussacana** [comment]
> Here are the steps to take
> 
> 1. launch panda app
> 2. plug in phone
> 3. launch terminal on PC and type :
>    `adb devices`
> 4. confirm the dialog box that pops up on your phone
> 5. in the terminal type
>    `adb root`
> 
> `adb shell sh /sdcard/.chaozhuo.gameassistant2/inject.sh`
> 
> 6. wait for about 20 seconds to see green confirmation in phone panda app
> 7. unplug phone from PC and enjoy game.

this can be done in termux as well if you have root

**Comment by iEscapedVim** [comment]
not working total waste of money and time useless peace of crap

**Comment by MarcosHenrique533** [comment]
Bjchj

**Comment by MarcosHenrique533** [comment]
Gjbb h
